### ISSUE TITLE
/addonline does not add anything to players

### ISSUE THREAD

**Issue by jemnidad** [Bibliofile/BHMB-Server-Currency#7]
I thought I submitted a similar issue.  I'm still seeing addonline fail to add currency to all the online players.

**Comment by Bibliofile** [comment]
Not sure what is causing this... I've looked through the code and it seems that it should be adding correctly... I haven't received any error reports, but that is somewhat broken right now. Do any errors appear in your dev console? (F12, console tab)

http://blockheadsfans.com/messagebot/extension/biblio_banks/code/430/447#l428

**Comment by jemnidad** [comment]
I don't see any console errors.  But you witnessed how it gave you twice
the normal amount and JD LOVES SADIE got nothing right?  Could my bank
files be messed up?  That would suck

J.

**Comment by jemnidad** [comment]
I did see these errors later.  Not sure what they relate to.  Maybe just
when I lost internet or my laptop went to sleep.

J

undefined:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON
at position 2(…)
undefined:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON
at position 2(…)

**Comment by Bibliofile** [comment]
> I don't see any console errors.  But you witnessed how it gave you twice the normal amount and JD LOVES SADIE got nothing right?  Could my bank files be messed up?  That would suck
> 
> J.

I suppose it is possible that those are messed up, I'm honestly lost as to how they could be messed up that this breaks though. 

> I did see these errors later.  Not sure what they relate to.  Maybe just when I lost internet or my laptop went to sleep.
> 
> J
> 
> undefined:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 2(…)
> undefined:1 Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 2(…)

That sounds to me like the Bibliophile/Blockheads-MessageBot#3 bug, I think the portal doesn't like it when the ID of messages gets too high... Not confirmed though.

**Comment by jemnidad** [comment]
The JD guy recently changed accounts for other reasons so I'll check next
time he's on if the addonline works on his new account.

J

**Comment by jemnidad** [comment]
Nobody has been online today to test with, but a thought occurred to me. What if it has something to do with the function that gets who is online?  As I recall there _might_ have been a player online who had special characters.  Seems like there's always someone since I don't forbid them on Arena.  If someone with special characters was in the listing prior to a normal player, would the online list get messed up?

**Comment by Bibliofile** [comment]
Very, very, late.. but yep, that's exactly what's happening. I looked at this code SO many times before seeing what was wrong. [The offending line](https://github.com/Bibliofile/Blockheads-MessageBot/blob/c3dd6b64106f17f2e729a9d0929f2a590a8a926b/dev/MessageBotCore.js#L207). 

The bot's online system is broken, it always assumes that the oldest player on the online list is the one who left rather than removing the person who actually left. I'll get a fix out for this this weekend hopefully.
